name: go-lint
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.19 
          cache: false
      - uses: actions/checkout@v3
      # - name: golangci-lint
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     version: latest
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ github.token }}
          level: warning
          golangci_lint_flags: "--config=.golintci.yml"
          filter_mode: nofilter
          reporter: github-pr-review
